DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS Employee;

CREATE TABLE Employee(
    EmployeeID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Password NVARCHAR(50) NOT NULL,
    Fname NVARCHAR(50) NOT NULL,
    Lname NVARCHAR(50) NOT NULL,
    Role NVARCHAR(50) NOT NULL,
    Address NVARCHAR(50) NOT NULL,
    Phone NVARCHAR(50) NOT NULL,
    Photo VARBINARY(MAX) NULL,
    ManagerID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Employee (EmployeeID),
    DateCreated DATETIME2 NOT NULL DEFAULT (GETDATE()),
    DateModified DATETIME2 NOT NULL DEFAULT (GETDATE())
);

CREATE TABLE Ticket(
    TicketID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Amount MONEY NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    Type NVARCHAR(100) NOT NULL,
    Status NVARCHAR(50) NOT NULL,
    Receipt VARBINARY(MAX) NULL,
    FK_EmployeeID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Employee (EmployeeID),
    FK_ProcessingManagerID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Employee (EmployeeID),
    DateCreated DATETIME2 NOT NULL DEFAULT (GETDATE()),
    DateModified DATETIME2 NOT NULL DEFAULT(GETDATE()),
    DateProcessed DATETIME2
)